<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SmartReview.Worker-d1d5e970-2d1e-432b-a87d-9cbf421ee876</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartReview.Infrastructure\SmartReview.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartReview.Application\SmartReview.Application.csproj" />
    <ProjectReference Include="..\SmartReview.Core\SmartReview.Core.csproj" />
  </ItemGroup>
</Project>
